"""add username and role enum to users

Revision ID: 37490e1a0463
Revises: 3ce39395ca90
Create Date: 2026-08-11 16:06:35.564584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37490e1a0463'
down_revision = '3ce39395ca90'
branch_labels = None
depends_on = None


def upgrade():
    userrole_enum = sa.Enum('buyer', 'seller', 'admin', 'superadmin', name='userrole')
    userrole_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=75), nullable=True))
        batch_op.add_column(sa.Column('role', sa.ARRAY(userrole_enum), nullable=True))

    op.execute("UPDATE users SET username = split_part(email, '@', 1) WHERE username IS NULL")
    op.execute("UPDATE users SET role = ARRAY['buyer'::userrole] WHERE role IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=75),
               nullable=False)
               
        # Make the column NOT NULL and ensure any future raw inserts use an empty array default
        batch_op.alter_column('role',
               existing_type=sa.ARRAY(userrole_enum),
               nullable=False,
               existing_server_default=sa.text("'{}'::userrole[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
