"""alter orders layout and data types

Revision ID: 3ce39395ca90
Revises: 
Create Date: 2026-08-11 15:33:22.832453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce39395ca90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 1. Create the native PostgreSQL Enum type
    orderstatus_enum = sa.Enum('pending', 'processed', 'accepted', 'shipping', 'delivered', name='orderstatus')
    orderstatus_enum.create(op.get_bind())

    # 2. DATA CLEANUP: Run this before altering the column to prevent crashes
    op.execute("UPDATE orders SET name = 'unnamed_order' WHERE name IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        # FIXED: Drop the old server default first to prevent the casting collision!
        batch_op.execute("ALTER TABLE orders ALTER COLUMN status DROP DEFAULT")
        
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=orderstatus_enum,
               postgresql_using="lower(status)::orderstatus",
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        # FIXED: Re-apply the server default as the new Enum type
        batch_op.execute("ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'pending'::orderstatus")
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('orders_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('orders_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSED', 'ACCEPTED', 'SHIPPING', 'DELIVERED', name='orderstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
