"""add deleted at and change all to server_default

Revision ID: 503a9a24193e
Revises: bf1bb0ac101e
Create Date: 2026-08-19 09:49:26.308903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503a9a24193e'
down_revision = 'bf1bb0ac101e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
