"""add deleted_at to orders

Revision ID: 815a83d2ddfb
Revises: c7f2cbb27adc
Create Date: 2026-08-20 13:09:16.050211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815a83d2ddfb'
down_revision = 'c7f2cbb27adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
