"""add is active and sku to products

Revision ID: bf1bb0ac101e
Revises: 1a42d12c6f44
Create Date: 2026-08-19 09:14:37.718656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1bb0ac101e'
down_revision = '1a42d12c6f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True,server_default=sa.text('true')))
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###

    op.execute("UPDATE products SET is_active = TRUE WHERE is_active IS NULL")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sku')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
