"""fix junction mapping to string

Revision ID: c00af829578d
Revises: e5dadb8947a1
Create Date: 2026-08-12 00:39:47.809638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c00af829578d'
down_revision = 'e5dadb8947a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_itmes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_itmes',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_itmes_order_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_itmes_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('order_itmes_pkey'))
    )
    # ### end Alembic commands ###
