"""add payment_ref and payment_status to orders

Revision ID: c4376e96a7c7
Revises: 938979f6db37
Create Date: 2026-09-03 10:32:24.905915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4376e96a7c7'
down_revision = '938979f6db37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint('uq_orders_payment_ref', ['payment_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_payment_ref', type_='unique')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_ref')

    # ### end Alembic commands ###
