"""change role to roles user table

Revision ID: c7f2cbb27adc
Revises: 503a9a24193e
Create Date: 2026-08-19 15:01:32.555407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7f2cbb27adc'
down_revision = '503a9a24193e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 1. Add new column as nullable first
        batch_op.add_column(sa.Column('roles', postgresql.ARRAY(sa.Enum('BUYER', 'SELLER', 'ADMIN', 'SUPERADMIN', name='userrole')), nullable=True))
    
    # 2. Copy data from old column to new column
    op.execute("UPDATE users SET roles = role")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 3. Drop the old column
        batch_op.drop_column('role')
        # 4. Make the new column NOT NULL
        batch_op.alter_column('roles', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 1. Add old column as nullable first
        batch_op.add_column(sa.Column('role', postgresql.ARRAY(postgresql.ENUM('buyer', 'seller', 'admin', 'superadmin', 'BUYER', 'SELLER', 'ADMIN', 'SUPERADMIN', name='userrole')), autoincrement=False, nullable=True))
    
    # 2. Copy data from new column to old column
    op.execute("UPDATE users SET role = roles")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 3. Drop the new column
        batch_op.drop_column('roles')
        # 4. Make the old column NOT NULL
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###
