"""convert order_items to pure many to many table

Revision ID: e5dadb8947a1
Revises: 37490e1a0463
Create Date: 2026-08-11 20:07:29.501409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5dadb8947a1'
down_revision = '37490e1a0463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'id')
    op.drop_column('order_items', 'quantity')

    op.create_primary_key(
        'pk_order_items', 
        'order_items', 
        ['orders_id', 'product_id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orders_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['orders_id'], ['orders.id'], name=op.f('order_items_orders_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_items_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.drop_table('order_itmes')
    # ### end Alembic commands ###
